// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Button = {};

var Label = {};

var Options = {};

var $$Option = {};

exports.Button = Button;
exports.Label = Label;
exports.Options = Options;
exports.$$Option = $$Option;
/* No side effect */
