// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Button = {};

var Items = {};

var Item = {};

exports.Button = Button;
exports.Items = Items;
exports.Item = Item;
/* No side effect */
